'use client';
import {useEffect,useState} from 'react';
import {db,configured,tables,TableName} from '../lib/db';
import type {Session} from '@supabase/supabase-js';

export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[section,setSection]=useState<'dashboard'|TableName>('dashboard'),[counts,setCounts]=useState<Record<string,number>>({}),[message,setMessage]=useState('');
 const adminEmail=process.env.NEXT_PUBLIC_ADMIN_EMAIL?.toLowerCase().trim();
 const allowed=!!session?.user.email&&!!adminEmail&&session.user.email.toLowerCase()===adminEmail;
 useEffect(()=>{if(!db){setReady(true);return}db.auth.getSession().then(({data})=>{setSession(data.session);setReady(true)});const {data:s}=db.auth.onAuthStateChange((_e,x)=>setSession(x));return()=>s.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!db||!allowed||section!=='dashboard')return;Promise.all(Object.keys(tables).map(k=>db.from(k).select('*',{count:'exact',head:true}))).then(r=>setCounts(Object.fromEntries(Object.keys(tables).map((k,i)=>[k,r[i].count??0]))))},[allowed,section]);
 async function signIn(e:React.FormEvent){e.preventDefault();setMessage('');if(!db)return;const {error}=await db.auth.signInWithPassword({email,password});if(error)setMessage('تعذر تسجيل الدخول. تحقق من البريد وكلمة المرور.');setPassword('')}
 if(!ready)return <div className="center">جارٍ تجهيز البوابة…</div>;
 if(!configured)return <div className="center"><div className="card"><div className="logo">و</div><h1>بوابة وصول</h1><p>أضف متغيرات Supabase في Vercel لتفعيل النظام.</p></div></div>;
 if(!session||!allowed)return <div className="center"><div className="card"><div className="logo">و</div><span>جمعية الأسر المنتجة بجازان</span><h1>بوابة إدارة وصول</h1>{session&&!allowed?<><p className="err">هذا الحساب غير مخوّل.</p><button onClick={()=>db?.auth.signOut()}>تسجيل الخروج</button></>:<form onSubmit={signIn}><input type="email" required placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)}/><button>دخول المدير</button></form>}{message&&<p className="err">{message}</p>}</div></div>;
 return <div className="shell"><aside><div className="brand"><div className="logo">و</div><div><b>وصول</b><small>بوابة إدارة المشروع</small></div></div><nav><button className={section==='dashboard'?'active':''} onClick={()=>setSection('dashboard')}>لوحة التحكم</button>{Object.entries(tables).map(([k,v])=><button key={k} className={section===k?'active':''} onClick={()=>setSection(k as TableName)}>{v.title}</button>)}</nav><button className="logout" onClick={()=>db?.auth.signOut()}>تسجيل الخروج</button></aside><main><header><div><small>لوحة الإدارة / مشروع وصول</small><h1>{section==='dashboard'?'نظرة عامة':tables[section].title}</h1></div></header>{section==='dashboard'?<><section className="hero"><div><span>إدارة أكثر وضوحًا</span><h2>مرحبًا بك في بوابة وصول</h2><p>نظام مستقل لإدارة المشروع ومتابعة بياناته.</p></div></section><section className="stats">{Object.entries(tables).map(([k,v])=><button key={k} onClick={()=>setSection(k as TableName)}><span>{v.title}</span><strong>{counts[k]??0}</strong><small>إجمالي السجلات</small></button>)}</section></>:<section className="panel"><h2>{tables[section].title}</h2><p>تم تجهيز هذا القسم للربط بقاعدة البيانات. سنضيف شاشة السجلات والإضافة والتعديل في المرحلة التالية.</p></section>}</main></div>
}
