'use client';
import type {Field,Row,Section,Config} from './portal-config';
import {dateAr,labels,money,titles} from './portal-config';

export function FieldInput({field,value,onChange}:{field:Field;value:any;onChange:(v:any)=>void}){
 if(field.type==='select')return <select value={value??''} onChange={e=>onChange(e.target.value)}><option value="">اختر</option>{field.options?.map(o=><option key={o} value={o}>{o}</option>)}</select>;
 if(field.type==='checkbox')return <label className="check-line"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/><span>{value?'مكتمل':'غير مكتمل'}</span></label>;
 return <input type={field.type||'text'} required={field.required} value={value??''} onChange={e=>onChange(field.type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)}/>;
}

export function Editor({fields,form,setForm,editing,onSave,onCancel}:{fields:Field[];form:Row;setForm:any;editing:Row|null;onSave:any;onCancel:any}){return <form className="editor" onSubmit={onSave}><div className="editor-head"><h4>{editing?'تعديل السجل':'إضافة سجل جديد'}</h4><button type="button" onClick={onCancel}>×</button></div><div className="form-grid">{fields.map(f=><label key={f.key}><span>{f.label}</span><FieldInput field={f} value={form[f.key]} onChange={v=>setForm((x:Row)=>({...x,[f.key]:v}))}/></label>)}</div><div className="form-actions"><button className="primary" type="submit">حفظ البيانات</button><button type="button" onClick={onCancel}>إلغاء</button></div></form>}

export function Toolbar({search,setSearch,right}:{search:string;setSearch:(v:string)=>void;right?:any}){return <div className="toolbar"><div className="search-box"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث بالاسم، اللوحة، العقد، المطالبة..."/></div><div className="toolbar-actions">{right}</div></div>}

export function Dashboard({totals,groups,critical}:{totals:any;groups:[string,number][];critical:any[]}){return <><section className="hero"><div><span className="hero-label">مركز قيادة مشروع وصول</span><h2>الصورة التشغيلية الكاملة في شاشة واحدة</h2><p>التحصيل، المستفيدون، المركبات، الحوادث، الموافقات والمهام.</p></div><div className="hero-badge"><strong>{totals.count}</strong><span>مستفيدًا</span></div></section><section className="kpis six"><K label="المستفيدون" value={totals.count}/><K label="إجمالي الدخل" value={totals.income.toLocaleString('ar-SA')}/><K label="المتأخرات" value={totals.overdue} warn/><K label="المهام المفتوحة" value={totals.openTasks}/><K label="الموافقات المعلقة" value={totals.pendingApprovals}/><K label="الحوادث المفتوحة" value={totals.activeAccidents} warn/></section><section className="dashboard-grid"><div className="panel"><div className="panel-head"><div><span className="eyebrow">الحالات الحرجة</span><h3>ما يحتاج إجراء الآن</h3></div><span className="count-badge">{critical.length}</span></div><div className="critical-list">{critical.slice(0,10).map((c,i)=><div className={`critical-item ${c.level}`} key={i}><div><b>{c.type}</b><span>{c.title}</span></div><small>{dateAr(c.date)}</small></div>)}{critical.length===0&&<div className="empty-state">لا توجد حالات حرجة حاليًا.</div>}</div></div><div className="panel"><div className="panel-head"><div><span className="eyebrow">المركبات</span><h3>توزيع الأنواع</h3></div></div><div className="vehicle-bars">{groups.map(([name,count])=><div className="bar-row" key={name}><div><b>{name}</b><span>{count} مستفيد</span></div><div className="bar"><i style={{width:`${Math.max(10,(count/Math.max(totals.count,1))*100)}%`}}/></div></div>)}</div></div></section><section className="kpis four"><K label="الصافي" value={totals.net.toLocaleString('ar-SA')}/><K label="العائد" value={totals.returns.toLocaleString('ar-SA')}/><K label="مهام عالية/عاجلة" value={totals.urgent} warn/><K label="مستندات قريبة الانتهاء" value={totals.expiringDocs} warn/></section></>}
function K({label,value,warn}:{label:string;value:any;warn?:boolean}){return <div className={`kpi ${warn?'warn-kpi':''}`}><span>{label}</span><strong>{value}</strong><small>تحديث مباشر</small></div>}

export function Beneficiaries({rows,reports,fields,showForm,form,setForm,editing,add,edit,remove,save,cancel,search,setSearch,setProfile,exportCsv}:any){return <section className="panel"><div className="panel-head"><div><span className="eyebrow">قاعدة المستفيدين</span><h3>{reports.length} مستفيدًا</h3></div><button className="primary small" onClick={add}>+ إضافة مستفيد</button></div><Toolbar search={search} setSearch={setSearch} right={<button className="ghost" onClick={exportCsv}>تصدير CSV</button>}/>{showForm&&<Editor fields={fields} form={form} setForm={setForm} editing={editing} onSave={save} onCancel={cancel}/>}<div className="cards">{rows.map((r:Row)=><article className="person-card" key={r.id}><div className="person-top"><div className="avatar">{String(r.beneficiary_name||'و').charAt(0)}</div><div><small>مستفيد رقم {r.beneficiary_number??'—'}</small><h4>{r.beneficiary_name}</h4><span className="chip">{r.vehicle_type||'مركبة غير محددة'}</span></div></div><div className="person-stats"><div><span>الدخل</span><b>{money(r.quarterly_income)}</b></div><div><span>العائد</span><b>{money(r.total_return)}</b></div><div><span>الصافي</span><b>{money(r.net_after_return)}</b></div></div><div className="requirements">{[['التأمين',r.insurance_status],['رخصة السير',r.vehicle_registration_status],['العمل الحر',r.freelance_license_status],['التطبيقات',r.transport_apps_status]].map(([k,v])=><span key={String(k)} className={v==='مكتمل'?'ok':''}>{k}</span>)}</div><div className="actions"><button onClick={()=>setProfile(r)}>الملف الشامل</button><button onClick={()=>edit(r)}>تعديل</button><button className="danger" onClick={()=>remove(r)}>حذف</button></div></article>)}</div></section>}

export function Generic({section,rows,config,showForm,fields,form,setForm,editing,add,edit,remove,save,cancel,search,setSearch,showQr,criticalOnly,setCriticalOnly}:any){return <section className="panel"><div className="panel-head"><div><span className="eyebrow">إدارة السجلات</span><h3>{titles[section as Section]}</h3></div><button className="primary small" onClick={add}>+ إضافة سجل</button></div><Toolbar search={search} setSearch={setSearch} right={section==='followups'?<button className={criticalOnly?'primary small':'ghost'} onClick={()=>setCriticalOnly(!criticalOnly)}>الحالات المهمة فقط</button>:null}/>{showForm&&<Editor fields={fields} form={form} setForm={setForm} editing={editing} onSave={save} onCancel={cancel}/>}<div className="table-wrap"><table><thead><tr>{config.columns.map((c:string)=><th key={c}>{labels[c]||c}</th>)}{section==='vehicles'&&<th>QR</th>}<th>الإجراءات</th></tr></thead><tbody>{rows.map((r:Row)=><tr key={r.id}>{config.columns.map((c:string)=><td key={c}>{['monthly_amount','amount','paid_amount'].includes(c)?money(r[c]):['due_date','accident_date','expiry_date','requested_at','handover_date','request_date','transfer_date'].includes(c)?dateAr(r[c]):typeof r[c]==='boolean'?(r[c]?'نعم':'لا'):r[c]??'—'}</td>)}{section==='vehicles'&&<td><button className="mini" onClick={()=>showQr(r)}>عرض QR</button></td>}<td><div className="table-actions"><button onClick={()=>edit(r)}>تعديل</button><button className="danger" onClick={()=>remove(r)}>{config.archive?'أرشفة':'حذف'}</button></div></td></tr>)}</tbody></table>{rows.length===0&&<div className="empty-state">لا توجد سجلات بعد. اضغط «إضافة سجل» للبدء.</div>}</div></section>}

export function Audit({rows,search,setSearch}:{rows:Row[];search:string;setSearch:any}){return <section className="panel"><div className="panel-head"><div><span className="eyebrow">الشفافية والرقابة</span><h3>آخر التغييرات في المنصة</h3></div></div><Toolbar search={search} setSearch={setSearch}/><div className="timeline">{rows.map(r=><div className="timeline-item" key={r.id}><span className={`audit-dot ${String(r.action||'').toLowerCase()}`}/><div><b>{r.action==='INSERT'?'إضافة':r.action==='UPDATE'?'تعديل':'حذف'} — {r.table_name}</b><small>{dateAr(r.changed_at)} • {new Date(r.changed_at).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})}</small></div></div>)}</div></section>}

export function ProfileModal({person,data,onClose}:{person:Row;data:Record<string,Row[]>;onClose:()=>void}){const byName=(arr:Row[])=>arr.filter(x=>x.beneficiary_name===person.beneficiary_name&&!x.archived);const contracts=byName(data.contracts??[]),accidents=byName(data.accidents??[]),docs=byName(data.documents??[]),approvals=byName(data.approvals??[]),ownership=byName(data.ownership??[]);return <Modal title="ملف المستفيد الشامل" onClose={onClose}><div className="profile-hero"><div className="avatar big">{String(person.beneficiary_name||'و').charAt(0)}</div><div><h2>{person.beneficiary_name}</h2><span className="chip">{person.vehicle_type||'مركبة غير محددة'}</span></div></div><div className="profile-grid"><Info label="إجمالي الدخل" value={money(person.quarterly_income)}/><Info label="العائد" value={money(person.total_return)}/><Info label="الصافي" value={money(person.net_after_return)}/><Info label="العقود" value={contracts.length}/><Info label="الحوادث" value={accidents.length}/><Info label="المستندات" value={docs.length}/></div><div className="profile-sections"><ProfileList title="العقود" items={contracts.map(x=>`${x.reference||'—'} — ${x.status||'—'} — ${money(x.monthly_amount)}`)}/><ProfileList title="الحوادث" items={accidents.map(x=>`${dateAr(x.accident_date)} — ${x.repair_status||'—'} — ${x.claim_number||'بدون مطالبة'}`)}/><ProfileList title="الموافقات" items={approvals.map(x=>`${x.request_type} — ${x.status}`)}/><ProfileList title="نقل الملكية" items={ownership.map(x=>`${x.vehicle_plate||'—'} — ${x.status}`)}/></div>{person.notes&&<div className="note-box"><b>ملاحظات</b><p>{person.notes}</p></div>}</Modal>}
function Info({label,value}:{label:string;value:any}){return <div className="info-card"><span>{label}</span><b>{value}</b></div>}
function ProfileList({title,items}:{title:string;items:string[]}){return <div><h4>{title}</h4>{items.length?items.map((x,i)=><div className="profile-line" key={i}>{x}</div>):<span className="muted">لا توجد سجلات.</span>}</div>}
export function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:any}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h3>{title}</h3><button onClick={onClose}>×</button></div>{children}</div></div>}
