export type Row=Record<string,any>;
export type Section='dashboard'|'beneficiaries'|'vehicles'|'contracts'|'installments'|'maintenance'|'accidents'|'documents'|'approvals'|'handovers'|'ownership'|'followups'|'audit';
export type Field={key:string;label:string;type?:'text'|'number'|'date'|'select'|'checkbox';options?:string[];required?:boolean};
export type Config={table:string;fields:Field[];columns:string[];archive?:boolean};

export const titles:Record<Section,string>={dashboard:'لوحة التحكم',beneficiaries:'المستفيدون',vehicles:'المركبات',contracts:'العقود',installments:'الأقساط والتحصيل',maintenance:'التأمين والصيانة',accidents:'الحوادث والتأمين',documents:'المستندات',approvals:'الموافقات',handovers:'التسليم والاستلام',ownership:'نقل الملكية',followups:'المهام والمتابعات',audit:'سجل النشاط'};
export const money=(v:any)=>v===null||v===undefined||v===''?'—':`${Number(v).toLocaleString('ar-SA')} ر.س`;
export const dateAr=(v:any)=>v?new Date(v).toLocaleDateString('ar-SA'):'—';

export const beneficiaryFields:Field[]=[
 {key:'beneficiary_number',label:'رقم المستفيد',type:'number'},
 {key:'beneficiary_name',label:'اسم المستفيد',required:true},
 {key:'vehicle_type',label:'نوع المركبة'},
 {key:'quarterly_income',label:'إجمالي الدخل',type:'number'},
 {key:'total_return',label:'إجمالي العائد / الأقساط',type:'number'},
 {key:'net_after_return',label:'الصافي',type:'number'},
 {key:'freelance_license_status',label:'رخصة العمل الحر',type:'select',options:['مكتمل','غير مكتمل']},
 {key:'vehicle_registration_status',label:'رخصة السير',type:'select',options:['مكتمل','غير مكتمل']},
 {key:'insurance_status',label:'التأمين',type:'select',options:['مكتمل','غير مكتمل']},
 {key:'transport_apps_status',label:'تطبيقات النقل',type:'select',options:['مكتمل','غير مكتمل']},
 {key:'notes',label:'ملاحظات'}
];

export const configs:Partial<Record<Section,Config>>={
 vehicles:{table:'vehicles',fields:[{key:'plate_number',label:'رقم اللوحة',required:true},{key:'make_model',label:'الماركة والموديل'},{key:'model_year',label:'سنة الموديل',type:'number'},{key:'status',label:'الحالة',type:'select',options:['نشطة','صيانة','متوقفة']}],columns:['plate_number','make_model','model_year','status']},
 contracts:{table:'contracts',archive:true,fields:[{key:'reference',label:'مرجع العقد',required:true},{key:'beneficiary_name',label:'المستفيد'},{key:'vehicle_plate',label:'رقم اللوحة'},{key:'monthly_amount',label:'القسط الشهري',type:'number'},{key:'status',label:'الحالة',type:'select',options:['نشط','مكتمل','متأخر','متوقف']}],columns:['reference','beneficiary_name','vehicle_plate','monthly_amount','status']},
 installments:{table:'installments',archive:true,fields:[{key:'contract_reference',label:'مرجع العقد',required:true},{key:'due_date',label:'تاريخ الاستحقاق',type:'date'},{key:'amount',label:'المبلغ',type:'number'},{key:'paid_amount',label:'المبلغ المسدد',type:'number'},{key:'status',label:'الحالة',type:'select',options:['مسدد','مستحق','متأخر','مؤجل']}],columns:['contract_reference','due_date','amount','paid_amount','status']},
 maintenance:{table:'maintenance',archive:true,fields:[{key:'vehicle_plate',label:'رقم اللوحة',required:true},{key:'category',label:'التصنيف',type:'select',options:['تأمين','صيانة دورية','إصلاح','فحص']},{key:'due_date',label:'تاريخ الاستحقاق',type:'date'},{key:'status',label:'الحالة',type:'select',options:['سليم','مستحق','قيد التنفيذ','مكتمل']}],columns:['vehicle_plate','category','due_date','status']},
 accidents:{table:'accidents',archive:true,fields:[{key:'beneficiary_name',label:'المستفيد'},{key:'vehicle_plate',label:'رقم اللوحة'},{key:'accident_date',label:'تاريخ الحادث',type:'date'},{key:'fault_percentage',label:'نسبة الخطأ %',type:'number'},{key:'claim_number',label:'رقم المطالبة'},{key:'insurer',label:'شركة التأمين'},{key:'repair_status',label:'حالة الإصلاح',type:'select',options:['جديد','قيد المطالبة','تحت الإصلاح','مكتمل','هلاك كلي']},{key:'installment_effect',label:'أثر الحادث على الأقساط'},{key:'notes',label:'ملاحظات'}],columns:['beneficiary_name','vehicle_plate','accident_date','fault_percentage','claim_number','repair_status']},
 documents:{table:'documents',archive:true,fields:[{key:'beneficiary_name',label:'المستفيد'},{key:'vehicle_plate',label:'رقم اللوحة'},{key:'document_type',label:'نوع المستند',required:true,type:'select',options:['عقد','تأمين','استمارة','هوية','رخصة','حادث','خطاب','أخرى']},{key:'title',label:'عنوان المستند',required:true},{key:'file_url',label:'رابط الملف'},{key:'expiry_date',label:'تاريخ الانتهاء',type:'date'},{key:'status',label:'الحالة',type:'select',options:['نشط','منتهي','قريب الانتهاء']},{key:'notes',label:'ملاحظات'}],columns:['document_type','title','beneficiary_name','vehicle_plate','expiry_date','status']},
 approvals:{table:'approvals',archive:true,fields:[{key:'request_type',label:'نوع الطلب',required:true,type:'select',options:['تأجيل قسط','إعادة جدولة','تعديل عقد','استبدال مستفيد','صيانة استثنائية','نقل ملكية','أخرى']},{key:'subject',label:'الموضوع',required:true},{key:'details',label:'التفاصيل'},{key:'requested_by',label:'مقدم الطلب'},{key:'status',label:'الحالة',type:'select',options:['قيد المراجعة','معتمد','مرفوض']},{key:'decision_note',label:'ملاحظة القرار'}],columns:['request_type','subject','requested_by','status','requested_at']},
 handovers:{table:'vehicle_handovers',archive:true,fields:[{key:'beneficiary_name',label:'المستفيد'},{key:'vehicle_plate',label:'رقم اللوحة'},{key:'handover_type',label:'نوع الإجراء',type:'select',options:['تسليم','استلام']},{key:'handover_date',label:'التاريخ',type:'date'},{key:'odometer',label:'عداد الكيلومترات',type:'number'},{key:'fuel_level',label:'مستوى الوقود'},{key:'exterior_status',label:'حالة الهيكل الخارجي'},{key:'interior_status',label:'حالة الداخلية'},{key:'keys_count',label:'عدد المفاتيح',type:'number'},{key:'notes',label:'ملاحظات'}],columns:['beneficiary_name','vehicle_plate','handover_type','handover_date','odometer']},
 ownership:{table:'ownership_transfers',archive:true,fields:[{key:'beneficiary_name',label:'المستفيد'},{key:'vehicle_plate',label:'رقم اللوحة'},{key:'contract_reference',label:'مرجع العقد'},{key:'request_date',label:'تاريخ الطلب',type:'date'},{key:'payment_complete',label:'السداد مكتمل',type:'checkbox'},{key:'documents_complete',label:'المستندات مكتملة',type:'checkbox'},{key:'violations_clear',label:'المخالفات مسددة',type:'checkbox'},{key:'insurance_clear',label:'التأمين سليم',type:'checkbox'},{key:'status',label:'الحالة',type:'select',options:['تحت الإجراء','جاهز للنقل','تم النقل','موقوف']},{key:'transfer_date',label:'تاريخ النقل',type:'date'},{key:'notes',label:'ملاحظات'}],columns:['beneficiary_name','vehicle_plate','contract_reference','request_date','status','transfer_date']},
 followups:{table:'followups',archive:true,fields:[{key:'subject',label:'موضوع المهمة',required:true},{key:'due_date',label:'تاريخ الاستحقاق',type:'date'},{key:'priority',label:'الأولوية',type:'select',options:['منخفضة','متوسطة','عالية','عاجلة']},{key:'assigned_to',label:'المسؤول'},{key:'status',label:'الحالة',type:'select',options:['مفتوح','قيد المتابعة','مكتمل','متأخر']}],columns:['subject','due_date','priority','assigned_to','status']}
};

export const labels:Record<string,string>={plate_number:'اللوحة',make_model:'المركبة',model_year:'الموديل',reference:'مرجع العقد',beneficiary_name:'المستفيد',vehicle_plate:'اللوحة',monthly_amount:'القسط',status:'الحالة',contract_reference:'مرجع العقد',due_date:'التاريخ',amount:'المبلغ',paid_amount:'المسدد',category:'التصنيف',subject:'الموضوع',accident_date:'تاريخ الحادث',fault_percentage:'نسبة الخطأ',claim_number:'المطالبة',repair_status:'الإصلاح',document_type:'نوع المستند',title:'العنوان',expiry_date:'الانتهاء',request_type:'نوع الطلب',requested_by:'مقدم الطلب',requested_at:'تاريخ الطلب',handover_type:'الإجراء',handover_date:'التاريخ',odometer:'العداد',priority:'الأولوية',assigned_to:'المسؤول',transfer_date:'تاريخ النقل'};
